copy-section-value: copy added/removed lines
magit/magit pull request #4270
Opened 2020-12-18 22:02 UTC by qwerbzuio

Make it possible to copy only added/removed lines via a
positive/negative prefix arg.

----

2020-12-20 14:37 UTC, tarsius requested changes

2020-12-20 14:37 UTC, tarsius commented on lisp/magit-extras.el
> +      (let* ((magit-diff-sign-regexp
No need to namespace this. Since this can only be accessed within this function something like `re` is good enough.

2020-12-20 14:37 UTC, tarsius commented on lisp/magit-extras.el
> +              (lambda (str)
Just define this function where it is used below instead of binding some variable to it.

2020-12-20 14:37 UTC, tarsius commented on lisp/magit-extras.el
> +         (-filter (apply-partially magit-diff-filter-func)
Use `seq-filter` instead.

It makes no sense to use `apply-partially` and then not provide any arguments.

2020-12-21 18:50 UTC, tarsius commented
IMO this simpler version would be better: https://github.com/magit/magit/compare/keep-region-side.

2020-12-22 04:15 UTC, kyleam commented
@qwerbzuio Nice idea.  Seems like an obvious improvement, but it didn't occur to me when writing the initial "strip markers" variant or afterwards when using the functionality fairly regularly.

> IMO this simpler version would be better: https://github.com/magit/magit/compare/keep-region-side.

Looks good, aside from using cl-minusp instead `(< x 0)` :)

Perhaps already planned with the final patch, but just in case: the manual needs an update as well.

2020-12-22 10:48 UTC, tarsius commented
> Looks good, aside from using cl-minusp instead `(< x 0)` :)

Okay, I fixed that. :P

2020-12-22 11:31 UTC, closed without merging