Add "Unsaved changes" section inserter, and accompanying functionality
magit/magit pull request #4290
Opened 2021-01-12 19:49 UTC by CyberShadow

#4285

Sorry for the disorganized notes, I will clean these up later

- [ ] Implement the section
  - [X] Enumerate modified buffers belonging to the repository
    - [ ] Also add entries for buffers visiting files that don't yet exist - show them as "new file"
  - [X] Show diff between buffer and file on disk
- [ ] Section operations
  - [ ] <kbd>RET</kbd> (`magit-visit-thing`)
    - [ ] ~~on section~~ (`magit-diff-unsaved`? show all unsaved in a new buffer?)
    - [X] on file (go to buffer)
    - [X] on hunk (go to line in buffer)
      - [X] on deleted line in hunk (go to line in original file on disk)
  - [ ] <kbd>k</kbd> (`magit-delete-thing` / `magit-discard-unsaved`)
    - [ ] on section (revert all)
    - [ ] on file (revert file)
    - [ ] on hunk??
  - [ ] <kbd>C-x C-s</kbd> (?) (`write-file` / `magit-save`)
    - [ ] on section (save all)
    - [ ] on file (save file)
    - [ ] on hunk??
  - [ ] Stage? (prompt to save, then stage?)
    - [ ] Maybe it will work for hunks too (if they still apply)? Just throw the diff we have at git and see what happens.

- [ ] `magit-buffer-diff-files` ???

- [ ] Test
  - [X] Local repositories
  - [ ] Remote repositories

- [ ] Implementation
  - [ ] the &rest args !!!
    - [ ] Which of these new functions should be public?
  - [ ] `magit--prepare-buffer-coding`? Does it mutate the input buffer? Was that an OK thing to do previously?

2021-01-12 19:53 UTC, CyberShadow commented on lisp/magit-git.el
> +(defun magit--git-insert-with-input (input &rest args)
Here and elsewhere, the `&rest args` have posed an obstacle to extending the process functions.

Some alternative approaches:

- Pass the input via a global :nauseated_face: 
- If the first item in `args` is a buffer or `nil`, assume it's the optional `input` argument
- Introduce `fun-1` variants which don't use `&rest`, and thus are extensible
- Just change the function signature? It would be a breaking change but I don't know what impact that would have in practice.

2021-01-13 18:25 UTC, CyberShadow commented
I believe this is ready for initial review.

Outstanding points:

- The `&rest args` issue above.
- I made all new function declarations private (`magit--`). Perhaps some of these could be public and documented in the manual.
- One detail in the logic for finding buffers to diff depends on the resolution of #4292, which lies in code with a lot of history that I don't have the experienced to tackle.
- I'm not sure if `magit--process-input` needs to do the same `encode-coding-region` call as `magit-run-git-with-input`. For one, we are now piping in data to diff, as opposed to diffs to apply, but of course that's not reflected in the process creation API, so maybe that call needs to be higher up? For two, `magit-run-git-with-input` assumed that its input buffer was temporary and thus was safe to modify, but that doesn't apply to `magit--process-input`.

2021-01-13 18:37 UTC, CyberShadow commented on lisp/magit-git.el
> +(defun magit--git-insert-with-input (input &rest args)
> Here and elsewhere

Oops, actually, just here (if we don't count `magit--git-wash-fun`). There were more, but I refactored them away.

2021-01-17 10:37 UTC, tarsius commented
I have applied the first tree commits after regenerating `magit.texi`, so you'll have to rebase.

2021-01-17 10:38 UTC, CyberShadow commented
Thanks, done!

2021-01-17 10:55 UTC, tarsius commented
I was not expecting something like this and while I appreciate the careful work that went into this I am undecided whether to merge this and what parts I would want to be changed. (But there's hope.)

For now I think the first commit should implement a much simpler version of `magit-insert-unsaved-changes` that just lists the unsaved buffers (using the file-name but without a diff). `RET` should visit the buffer. But that's about it. I would then cherry-pick that. I don't have the time to have a discussion about the rest right now.

2021-01-17 13:31 UTC, CyberShadow commented
> For now I think the first commit should implement a much simpler version of `magit-insert-unsaved-changes` that just lists the unsaved buffers (using the file-name but without a diff). `RET` should visit the buffer. But that's about it.

Okay, done :)

2021-01-17 14:18 UTC, tarsius requested changes

2021-01-17 14:18 UTC, tarsius commented on lisp/magit-diff.el
> +  "Insert section showing unsaved changes in buffers."
Not yet. Please adjust.

2021-01-17 14:18 UTC, tarsius commented on lisp/magit-diff.el
> +  (when-let ((topdir (magit-toplevel)))
Why `when-let`? Once we get here it is well established that we are inside a git repository.

2021-01-17 14:30 UTC, CyberShadow commented on lisp/magit-diff.el
> +  "Insert section showing unsaved changes in buffers."
Alrighty, done (I used "a list of unsaved buffers")

2021-01-17 14:30 UTC, CyberShadow commented on lisp/magit-diff.el
> +  (when-let ((topdir (magit-toplevel)))
You're right, done

2021-01-19 13:22 UTC, CyberShadow commented
> I don't have the time to have a discussion about the rest right now.

No problem. Thank you.

> magit-files: Implement {orig-worktree} pseudo-revision

I think I would like to revisit this before this is merged, as this concerns slightly more than the idea of unsaved buffers. Thinking about this in terms of user story, I see two distinct intentions: 1) go to a buffer (at this point in the diff) which contains (exactly) this side of the diff that the user can view (and copy code out of), and 2) go as closely as possible to this point in the diff in a buffer that the user can *edit*. So, <kbd>RET</kbd> in a diff would do the former, but <kbd>C-RET</kbd> would always do the latter.

My initial thought was that creating an additional buffer should probably be avoided if possible, as it's another buffer that the user has to manage (or at least kill), so I was thinking that `{worktree}` should just do what `{orig-worktree}` does when a buffer exists visiting that file and it has modified. However, that would mess with muscle memory, and the user would now need to stop and think before killing the buffer if that's a buffer they want to keep or kill. (Even if the buffer is unmodified, killing it would lose the undo history, for example.) In any case, instead of `{orig-worktree}`, there should perhaps be `{worktree-or-buffer}` OSLT (used by <kbd>C-RET</kbd>), which always tries to create or find a suitable buffer and point within it, even if it has been modified.

2021-02-27 15:27 UTC, tarsius commented
IMO this implements some sort of secondary index. It is like Git's index but obviously much less mature. I think this is a mistake as it adds a lot of complexity and yet to be discovered bugs/missing features that I would have to fix/implement over time.

I am sorry but I have to reject this.

2021-02-27 15:27 UTC, closed without merging

2021-02-27 15:37 UTC, CyberShadow commented
> IMO this implements some sort of secondary index. It is like Git's index but obviously much less mature.

I think this is not an accurate description of the functionality added in this pull request. It does represent the state in buffers as an additional layer above the working tree; if anything, the working tree is now more like an index than the buffers. The index is two layers down from Emacs buffers.

> I think this is a mistake as it adds a lot of complexity and yet to be discovered bugs/missing features that I would have to fix/implement over time.

I would have been happy to address those.

> I am sorry but I have to reject this.

Okay.

However, I am personally very happy with the functionality added here, and so would like to continue using Magit with this functionality, which means I will be maintaining my own fork of Magit.

I would like to make this fork of Magit public. Do you have any advice on the most proper way to do so? Or, do you know of an existing fork of Magit that I can contribute this improvement to instead?

I may be interested in helping maintain other improvements to Magit that you have rejected in the past. Any suggestions?

2021-02-27 15:54 UTC, tarsius commented
> I would like to make this fork of Magit public. Do you have any advice on the most proper way to do so? Or, do you know of an existing fork of Magit that I can contribute this improvement to instead?

Well it would be best if it were an *extension* instead of a *fork*, but that probably won't work here. In some cases you might be able to add a *new* command and add it in the appropriate new section specific keymap, but I doubt that would work for all or at least nearly all of what you are adding here. So that's probably not an option.

So a fork it is. Please clearly document the differences and tell users to ask you for help first. Other than that I cannot think of any advice or requests right now.

> I may be interested in helping maintain other improvements to Magit that you have rejected in the past. Any suggestions?

I have tried using the `wontadd` label when I reject a contribution or suggestion.

2021-02-27 15:57 UTC, tarsius commented
Don't try to add it to Melpa under a different name. That would only be accepted if you changed all symbol names and that would make it extremely frustrating to compare your fork with the canonical version.

If you want to make it installable using `package.el`, then you should provide your own elpa archive, which users can add in a way that shadows Melpa.

2021-02-27 16:19 UTC, CyberShadow commented
Great, thank you!