magit-branch/magit-checkout: add recurse-submodules option
magit/magit pull request #4330
Opened 2021-02-22 14:26 UTC by insi-eb

# Change description and rationale

When using submodules, having to switch the submodules manually after each (branch and) checkout operation is quite cumbersome, even with the nice "o u" keyboard shortcuts.

This PR adds the git option "--recurse-submodules" to the magit-branch (sub-) commands that checkout branches, and default-enables this option. If there are uncommitted changes on a submodule, the update will fail, so it should be safe to default-enable this as far as I can see.

I could not find any other way to enable this option with the existing magit configuration possibilities.

As this is my first elisp contribution anywhere, I wanted to get feedback to both the functionality, and, if that part is ok, the code changes.
I tried to follow the conventions from similar code elsewhere in the magit code, but if I did something wrong, I'd appreciate a pointer to the corresponding documentation (a "search for 'foo' in the elisp manual and carefully read it" would be good enough for me) so I can fix that.
I also looked for calls to the affected functions, but am not fully sure I found all of them.

I'm also quite willing to update the documentation if adding this minor piece of functionality is ok.

2021-02-22 16:07 UTC, tarsius requested changes

2021-02-22 16:07 UTC, tarsius commented on lisp/magit-branch.el
> +  (interactive (list (magit-read-other-branch-or-commit "Checkout") (magit-branch-arguments)))
Add this on a new line.

2021-02-22 16:07 UTC, tarsius commented on lisp/magit-branch.el
> +  (interactive (list (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
This gives `((a b) c)` when we want `(a b c)`.

2021-02-22 16:07 UTC, tarsius commented on lisp/magit-branch.el
> +      (magit-checkout branch (transient-args 'magit-branch))
Since you added `magit-branch-arguments`, also use it here.

2021-02-22 16:07 UTC, tarsius commented on lisp/magit-branch.el
> +(transient-define-suffix magit-checkout (revision args)
Let's make that optional to avoid having to adjust callers.

2021-02-22 16:07 UTC, tarsius commented on lisp/magit-branch.el
> +   ("-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
This shouldn't be enabled by default because it detaches HEAD and I think it should even be hidden by default.

2021-02-22 16:27 UTC, insi-eb commented on lisp/magit-branch.el
> +   ("-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
ok, I can see that detaching HEAD might break other people's workflows. I'll check how I can make default-enabling and default-showing this configurable via the magit-group options, as I'd very much like to have that for my workflow.

btw, what is the rationale for default-hiding? just uncluttering the interface for a probably rare use-case or something eles in addition to that?
It would probably also make sense to list the option to default-show this option underneath the magit-submodule documentation in addition to the magit-branch documentation, wouldn't it? at least that is where I looked first for something like this.

2021-02-22 23:36 UTC, kyleam commented
> If there are uncommitted changes on a submodule, the update will fail, so it should be safe to default-enable this as far as I can see.

Unfortunately there's still an outstanding bug in git where `git checkout --recurse-submodules ...` will discard modifications in submodules.

https://lore.kernel.org/git/20200525094019.22padbzuk7ukr5uv@overdrive.tratt.net/

> I could not find any other way to enable this option with the existing magit configuration possibilities.

Depending on the user's preferences/workflow, one option is to set `submodule.recurse` to true.  That of course isn't desirable for those that don't always want to recurse with all the commands that that option affects.

2021-02-22 23:48 UTC, kyleam commented on lisp/magit-branch.el
> +   ("-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
Additional things to note when considering whether to show this by default:

  * the outstanding bug that I linked to in my other reply

  * this isn't available until 2.13 (which is more recent than magit's current minimum git version)

    Perhaps it's worth guarding this option in the same way the bisect transient does:
    `:if (lambda () (version<= "2.13" (magit-git-version)))`

2021-02-24 16:44 UTC, insi-eb commented on lisp/magit-branch.el
> +   ("-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
thanks for the feedback, I'll try to guard the option and not enable/show this by default as soon as I've fixed some of the other findings here

2021-02-24 16:45 UTC, insi-eb commented on lisp/magit-branch.el
> +  (interactive (list (magit-read-other-branch-or-commit "Checkout") (magit-branch-arguments)))
done

2021-02-24 16:45 UTC, insi-eb commented on lisp/magit-branch.el
> +      (magit-checkout branch (transient-args 'magit-branch))
done

2021-02-24 16:48 UTC, insi-eb commented on lisp/magit-branch.el
> +  (interactive (list (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
it looks like I need to dig through the elisp manual (and perhaps my good old copy of Abelson and Sussmann), as my first attempts here failed ... I will fix this and (re-)learn something

2021-02-25 08:43 UTC, insi-eb commented on lisp/magit-branch.el
> +  (interactive (list (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
fixed

2021-02-25 08:46 UTC, insi-eb commented on lisp/magit-branch.el
> +(transient-define-suffix magit-checkout (revision args)
fixed

2021-02-25 10:24 UTC, insi-eb commented on lisp/magit-branch.el
> +   ("-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
I've added user options to show and default-enable this, in addition the git-version is checked as proposed. If that is ok, I'd take a shot at updating the user documentation so that people are aware of these options.

2021-02-25 10:32 UTC, insi-eb commented on lisp/magit-branch.el
> +(transient-define-suffix magit-checkout (revision &optional args)
changing this from defun to transient-define-suffix adds warnings to the build
`Warning: ‘magit-checkout’ is for interactive use only`

is there any way to keep the defun and create a transient-suffix just from the existing function? I've skimmed the transient documentation for something like this, but nothing really popped out. If there is a specific section in that documentation I should read in detail for this, could someone point me to it?

2021-02-25 17:10 UTC, tarsius commented
These two options are not necessary. This essentially accomplishes the same:

```diff
-   ("-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
+  (7 "-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
```

2021-02-25 17:11 UTC, tarsius commented
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

2021-02-25 17:11 UTC, tarsius commented
The infix arguments used by a certain transient popups can be [set/saved](https://magit.vc/manual/transient/Saving-Values.html) for future invocations.  TL;DR Enter the transient as usual, enable and/or disable arguments, and finally type <kbd>C-x s</kbd> or <kbd>C-x C-s</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

2021-02-26 10:47 UTC, insi-eb commented
> These two options are not necessary. This essentially accomplishes the same:
> 
> ```diff
> -   ("-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
> +  (7 "-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
> ```

Thanks for the hint.

I actually did look at the levels feature of transient some weeks before I started adding the functionality, but promptly forgot about it afterwards. I will update both the code and documentation.

2021-02-26 12:10 UTC, insi-eb commented on lisp/magit-branch.el
> +   ("-r" "Recurse submodules when checking out an existing branch" "--recurse-submodules")]
I believe this is solved now. I will resolve the GitHub conversation if no one complains soon

2021-02-26 12:13 UTC, tarsius commented on lisp/magit-branch.el
> +  (interactive (append (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
And now it is `(a b c d)` when we want `(a b (c d))`.

2021-02-26 12:14 UTC, tarsius commented on Documentation/magit.org
> +
We don't document individual arguments in the manual.

2021-02-26 12:15 UTC, tarsius commented on lisp/magit-branch.el
> +  :value '("--recurse-submodules")
You are still enabling this by default. Please don't.

2021-02-26 12:16 UTC, tarsius commented on lisp/magit-branch.el
> +    :if (lambda ()
Merge the next line into this one and indent correctly.

2021-02-26 12:16 UTC, tarsius commented on lisp/magit-branch.el
> +  (interactive (append (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
(And this should be two lines, especially once you have added the `(list ...)`.

2021-02-26 12:22 UTC, tarsius commented on lisp/magit-branch.el
> +(transient-define-suffix magit-checkout (revision &optional args)
Why do you want to use `transient-define-suffix`? I don't see a need for that here. You don't need to do this to use `transient-args`.

2021-02-26 12:28 UTC, insi-eb commented on Documentation/magit.org
> +
to be honest, I would find that sometimes helpful. But I can remove it again, of course.

2021-02-26 12:28 UTC, insi-eb commented on lisp/magit-branch.el
> +  :value '("--recurse-submodules")
right, will remove

2021-02-26 12:42 UTC, insi-eb commented on lisp/magit-branch.el
> +  (interactive (append (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
I'm not sure I understand what's wrong here now, sorry for possibly being dense.

The previous finding was 
> This gives ((a b) c) when we want (a b c).
and the code really was not working right.

now magit-branch-read-args produces (a b), magit-branch-arguments produces (c), append should produce (a b c), and that is as it should be, shouldn't it, as there are 3 arguments to the function (one being optional)?

2021-02-26 14:54 UTC, tarsius commented on lisp/magit-branch.el
> +  (interactive (append (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
In the future there might be two arguments. Then we would get `(a b "--foo" "--bar")`, which does not match the function signature. We need:

```lisp
(append (magit-branch-read-args "Create and checkout branch")
        (list (magit-branch-arguments)))
```

or

```lisp
`(,@(magit-branch-read-args "Create and checkout branch")
  ,(magit-branch-arguments))
```

2021-02-26 15:09 UTC, insi-eb commented on lisp/magit-branch.el
> +  (interactive (append (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
ok, understood, thanks!

just out of curiosity, adding `&rest` to the signature would also make this as future-proof, wouldn't it?

2021-02-26 15:14 UTC, tarsius commented on lisp/magit-branch.el
> +  (interactive (append (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
Yes, but that's not how we do it for the "arguments for git" `ARGS` argument.

2021-02-26 15:23 UTC, insi-eb commented on lisp/magit-branch.el
> +  (interactive (append (magit-branch-read-args "Create and checkout branch") (magit-branch-arguments)))
hopefully fixed now

2021-02-27 13:43 UTC, merged