Sparse checkout and partial clone support
magit/magit pull request #4584
Opened 2022-01-18 02:33 UTC by kyleam

Commits 1-5 add support for `git sparse-checkout`.  The second commit is the main addition, and its commit message has some background on sparse checkouts and explains which aspects the new magit-sparse-checkout.el library targets.

Commit 6 adds partial clone support by adding `--filter` to `magit-clone`.  Although they can work together, partial clones aren't inherently coupled to sparse checkouts, but I decided to include the last commit given that both features share the same issue (gh-4102).

Closes #4102.

cc @aseltmann

---

I'm marking this as a draft, mostly because I've run out time to read over this tonight (apologies for bad typos or half-thoughts that may have slipped through).  I think it's likely that I won't get back to this until next weekend, but I'd of course be happy for any feedback in the meantime.

- [ ] regenerate manual

2022-01-22 23:53 UTC, tarsius commented
Sounds good to me.  I haven't actually tested anything but I have read the changes and descriptions and I liked what I saw.  Feel free to merge.

Since the man-page WARNS that things are likely to change, we might want to do the same.  IMO it would be okay if something changes upstream in a backward incompatible way, that we then require users to update to the Git version with the breaking change.  Of course if is trivial to continue to support older versions, then we should do that.  But given the fat upstream warning, we should probably have one too.

> There are other examples of --x/--no-x options along with an associated config knob (e.g., --recurse-submodules in magit-branch) that we don't bother supporting (in terms of having both options available in the transient or considering the configured value).

Yeah, I should really tackle that soon. ;)

2022-01-22 23:54 UTC, tarsius requested changes
that makes improves -> that improves

2022-01-22 23:56 UTC, tarsius commented on lisp/magit-clone.el
> +    :level 6)
To me that sounds like a "level 7" argument.

2022-01-23 03:16 UTC, kyleam commented on lisp/magit-clone.el
> +    :level 6)
Okay, will update.

2022-01-23 03:17 UTC, kyleam commented
> Since the man-page WARNS that things are likely to change, we might want to do the same. [...]

Right, good idea.  Will do.

> that makes improves -> that improves

Oops, thanks.

2022-01-23 21:46 UTC, merged