Add hook `magit-after-successful-clone-hook'
magit/magit pull request #4849
Opened 2023-01-20 16:03 UTC by nbarrientos

I vaguely remember somebody trying to add something like this to Magit in the past but not sure it has been proposed in this context. My apologies in advance if this has been already deemed not necessary.

I need to run code after a new repository is cloned, but only after the Git process has successfully finished. What I want to do is to add the repository to the project's database. 

Before, I was doing something like this:

```lisp
(defun my/magit-maybe-remember-project (repository directory args)
    (when (file-directory-p directory)
      (project-remember-project (cons 'vc (format "%s" (abbreviate-file-name directory))))))
(advice-add 'magit-clone-internal :after #'my/magit-maybe-remember-project)
```

However this is not good enough as there's a race condition between Git finishing (async process) and my code being executed. It could happen that `magit-clone-internal` exits but `directory` does not exist *yet*. The `when` guard is necessary because the repository may also fail to clone, hence the need to execute code only *after* a *successful* clone operation.

This patch adds a new hook allowing user code to be executed right after the Git `clone` process has exited 0, which guarantees that the repository has been correctly cloned and the target directory exists. The hook can be used like this:

```lisp
(defun my/magit-remember-project (repository directory)
  (project-remember-project (cons 'vc (format "%s" (abbreviate-file-name directory)))))
(add-hook 'magit-after-successful-clone-hook #'my/magit-remember-project)
```

Thanks.

2023-01-22 18:34 UTC, tarsius commented
> I vaguely remember somebody trying to add something like this to Magit in the past but not sure it has been proposed in this context.

I usually oppose the addition of "after `git something`" hooks, because with a little more work one can usually use the respective githook. (`emacs` new `--script` argument makes that easier, otherwise more boilerplate is required, as described at https://gist.github.com/ctarbide/99b0ac9f7d6bef19cdd3e9f71b4cbcf7).

But this seems more useful/necessary because there is no corresponding githook.

2023-01-22 18:40 UTC, tarsius requested changes

2023-01-22 18:40 UTC, tarsius commented on docs/magit.org
> +- User Option: magit-after-successful-clone-hook ::
You didn't actually define such a user option. I think you should.

I prefer a shorter name: `magit-post-clone-hook`.

2023-01-22 18:40 UTC, tarsius commented on lisp/magit-clone.el
> +         (run-hook-with-args 'magit-after-successful-clone-hook repository directory)
Why are you doing this here exactly and not earlier or later in the sentinel? Doing it at the very end seems reasonable to me.

2023-01-22 20:13 UTC, nbarrientos commented on docs/magit.org
> +- User Option: magit-after-successful-clone-hook ::
> You didn't actually define such a user option. I think you should.

Actually I did but I left it in my staging area :wink: Not sure about the value of `:package-version`, though. Please let me know.

> I prefer a shorter name: `magit-post-clone-hook`.

Sure, no problem. 

Both changes pushed and history rewritten.

2023-01-22 20:15 UTC, nbarrientos commented on lisp/magit-clone.el
> +         (run-hook-with-args 'magit-after-successful-clone-hook repository directory)
You're right, it's now placed right after all the extra `git` calls and before the status buffer is setup. Would that be fine?

2023-01-23 00:32 UTC, kyleam commented on lisp/magit-clone.el
> +         (run-hook-with-args 'magit-post-clone-hook repository directory)
Given this passes arguments, ideally the option wouldn't be named with "-hook" at the end (see `(info "(elisp)Hooks")`).  Or perhaps the hook doesn't need to be called with arguments, and it'd be sufficient to run it within the let-bound `default-directory` from line 284.

2023-01-23 08:45 UTC, nbarrientos commented on lisp/magit-clone.el
> +         (run-hook-with-args 'magit-post-clone-hook repository directory)
Hi Kyle,

Yes, it's probably a good idea to follow the conventions :grinning:. Indeed a hook that ends with `-hook` is expected to be argument-less.

I'm happy to change it to a "normal" hook, it'll cover sufficiently my user case assuming that `default-directory` is set to the directory where the repository has been cloned, as you're suggesting. This could be added as a note to the documentation of the hook so it's possible to know a bit about the context of the callback without having to look at the code.

However I think that adding it under the umbrella of the `let` clause you're suggesting wouldn't be enough as it's conditional to creating a sparse checkout. I could add another `let` block though right after the process finishes successfully, something like:

```diff
@@ -271,6 +271,8 @@ defun magit-clone-internal
            (magit-process-sentinel process event)))
        (when (and (eq (process-status process) 'exit)
                   (= (process-exit-status process) 0))
+         (let ((default-directory directory))
+           (run-hooks 'magit-post-clone-hook))
          (when checkout
            (let ((default-directory directory))
              (when set-push-default
``` 

It could also be at the very end as it is currently. 

Please let me know what you'd prefer.

2023-01-24 00:04 UTC, kyleam commented on lisp/magit-clone.el
> +         (run-hook-with-args 'magit-post-clone-hook repository directory)
> This could be added as a note to the documentation of the hook [...]

Right, if you go with the argument-less function, it should certainly be mentioned in the docs.

> However I think that adding it under the umbrella of the `let` clause you're suggesting wouldn't be enough [...]

Yes, sorry,  I didn't look closely enough at the context.

> It could also be at the very end as it is currently.

Like Jonas above, I think at the end seems like a natural spot.

2023-01-29 06:03 UTC, tarsius commented on lisp/magit-clone.el
> +         (run-hook-with-args 'magit-post-clone-hook repository directory)
It is generally preferred to use hooks without any arguments and if that is not possible, then convention is to name it `*-functions`. Here it seems unnecessary to use arguments; binding `default-directory` is enough and remote url can be retrieved from the git configuration if needed (as can other pieces of information one might need).

2023-01-29 06:04 UTC, tarsius requested changes
https://github.com/magit/magit/pull/4849/files#r1089873451

2023-01-29 08:07 UTC, nbarrientos commented on lisp/magit-clone.el
> +         (run-hook-with-args 'magit-post-clone-hook repository directory)
Agreed. The patch should be aligned now to what has been discussed :)

2023-02-06 10:28 UTC, nbarrientos commented
No hurry at all but just to make sure that we're not deadlocked waiting for each other this should be ready to be re-reviewed. Thanks again.

2023-02-06 11:38 UTC, merged

2023-02-06 11:51 UTC, tarsius commented
Sorry for the delay!