magit-base: consolidate ellipsis customisation
magit/magit pull request #4912
Opened 2023-04-01 12:14 UTC by nbarrientos

This patch centralises the generation of ellipses by extending the functionality provided by `magit-ellipsis`, allowing end users to customise for instance the ellipsis used in `magit-log` buffers.

See [discussions/4907](https://github.com/magit/magit/discussions/4907) for more background and extra information.

2023-04-01 13:19 UTC, tarsius requested changes

2023-04-01 13:19 UTC, tarsius commented on test/magit-tests.el
> +             (lambda (char) t)))
Thanks for adding tests!

Use `_` instead of `char` to keep the byte-compiler happy. Also put the lambda on the same line as the symbol-function.

2023-04-01 13:19 UTC, tarsius commented on lisp/magit-base.el
> +  '((magit-log (?… . ">"))
Lets go with `margin` instead of `magit-log` for now. (There is no need for a package prefix, and what makes it necessary to use a one-character ellipsis is the fact that we display information in the narrow `margin`. In the future we might display other things in some margin and need to truncate that information, and that might have nothing to do with `log`.

2023-04-01 13:19 UTC, tarsius commented on lisp/magit-base.el
> +    (nil       (?… . "...")))
The key for the default should be `t` instead of `nil`. Then use `(or where t)` below.

2023-04-01 13:19 UTC, tarsius commented on lisp/magit-base.el
> +\(WHERE (FANCY . UNIVERSAL))
Since it fits neatly, I would compress these three lines into just one.

2023-04-01 13:19 UTC, tarsius commented on lisp/magit-base.el
> +      (pcase-let ((`(,fancy . ,universal) (car (alist-get where magit-ellipsis default))))
The "default" key is the most used key, so I find it a bit odd to always look it up twice. I also think that error message below is worded as it is because of how you implemented this here. Simply saying that `magit-ellipsis` is invalid, seems more appropriate.

Speaking of invalid values, I think this should be backward compatible. There's no need to inform users that the format has been changed, and the old format should just be silently accepted.

2023-04-01 13:23 UTC, tarsius requested changes

2023-04-01 13:23 UTC, tarsius commented on lisp/magit-base.el
> +                             (choice string)))))
Please use `:tag "where"/"fancy"/"universal"` here, or similar.

2023-04-01 18:32 UTC, nbarrientos commented
Thanks for your comments! I've pushed separate commits fixing things so it's easier to re-review. Happy to change more stuff, just let me know. Otherwise, just ping me to squash :slightly_smiling_face: . Thanks.

2023-04-02 10:02 UTC, tarsius commented
Thanks!

> I haven't resolved the conversations myself and I don't know how you normally work in this regard.

I don't really use that much myself either.

2023-04-02 10:06 UTC, tarsius approved these changes

2023-04-02 10:06 UTC, merged

2023-04-02 12:44 UTC, nbarrientos commented
Thanks for merging! A :beer: is waiting for you in Genève :smile: